id: I32917B3F
legacy_id: P001855
ocr_import_info:
  bdrc_scan_id: W3CN3033
  source: bdrc
  ocr_info:
    timestamp: '2020-03-31T15:36:51'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T13:17:20.488337+00:00'
last_modified: 2022-09-03 21:17:41.629143
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN3033
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN3033
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསང་བདེ་འཇིགས་གསུམ་གྱི་རིམ་གཉིས་ཀྱི་ཁྲིད།
  author: ཤེས་རབ་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.9522998359878027
  ocr_word_median_confidence_index: 0.9900000095367432
quality: null
bases:
  I3CN3506:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN3506
      total_pages: 556
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN3506.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9522998359878027
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
